# Generated by Django 4.2.1 on 2023-12-22 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0003_tagteam_wrestlers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='length',
        ),
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
