# Generated by Django 4.2.1 on 2023-12-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0006_alter_tagteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagteam',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
