# Generated by Django 4.2.1 on 2023-12-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0008_alter_match_stipulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
