# Generated by Django 4.2.1 on 2023-12-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0002_remove_match_title_matchparticipant_champion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='img_src',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
