# Generated by Django 4.2.1 on 2023-12-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0004_alter_event_name_alter_match_stipulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
