# Generated by Django 4.2.1 on 2023-12-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling_matches', '0007_alter_tagteam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stipulation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
